config/routes.rb
Rails.application.routes.draw do
  get 'posts/view'

  get 'posts/posts'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users do
    resources :addresses
    resources :posts
  end
end

app/models/address.rb
# == Schema Information
#
# Table name: addresses
#
#  id         :integer          not null, primary key
#  city       :string
#  pincode    :integer
#  country    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Address < ApplicationRecord
  validates :city, :pincode, :country, presence: true
  validates :pincode, length: { is: 6 }

  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Post < ApplicationRecord
  validates :title, :content, presence:true

  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  password   :string
#  gender     :string
#  dob        :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
  validates :name, :email, :password, :gender, presence: { message: 'Field Cannot Be Empty' }
  validates :email, uniqueness: true, format: { with: /[\w.]*\@[\w]*\.[\w]*/ }
  #validates :gender, inclusion: { in: %w('Male', 'Female'), message: 'Valid Gender' }
  validates :password, length: { in: 6..32, message: 'is too short' }

  has_one :address
  has_many :posts

  before_create do
    puts 'Creating the Object....'
  end
  after_create do
    puts 'Object created Successfully...'
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def show
    @user = User.find(params[:id])
    @address = Address.find(params[:user_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to user_posts_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  def post_params
    post_data = {}
    post_data[:title] = params[:user][:title]
    post_data[:content] = params[:user][:content]
    post_data[:user_id] = params[:user_id]
    post_data
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  extend UsersHelper
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
    @address = Address.find_by(user_id: params[:id])
    @post = Post.find_by(user_id: params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @user }
     end
  end

  def new
    @user = User.new
    @parameters = ['name', 'email', 'password', 'gender', 'dob']
    respond_to do |format|
      format.html
      format.json { render json: @parameters }
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #render json: @user, status: :created
      redirect_to  users_path, status: :created
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :gender)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def readable_date(date)
    date.strftime('%a, %d %b %Y')
  end
end

app/views/addresses/show.html.haml
%h1 User Address
%ul
  %li
    %strong Name:
    #{@user.name}
  %li
    %strong City:
    #{@address.city}
  %li
    %strong Pincode:
    #{@address.pincode}
  %li
    %strong Country:
    #{@address.country}
=link_to('Back', user_path(@user))

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.haml
%h1 Newsfeed
%div
  - @posts.each do |post|
    %span
      %strong Title: #{post.title}
    %span #{post.created_at}
    %br/
    %span Content: #{post.content}
    %br/
    %br/
=link_to('Back', users_path)

app/views/posts/new.html.haml
%h1 Post

= form_tag user_posts_path, :method => :post do

  %p
    = label :post, :title, 'Title'
    %br/
    = text_field :user, :title

  %p
    = label :post, :content, 'Type Content'
    %br/
    = text_area :user, :content

  %p
    =link_to('Cancel', users_path)
    = submit_tag 'Submit'

app/views/posts/show.html.haml
%h1 User's Posts
%p
  -@posts.each do |post|
    %br/
    %div
      %strong Name:
      #{@user.name}
    %div
      %strong Title:
      #{post.title}
    %div
      %strong Content:
      #{post.content}
=link_to('Back', user_path)

app/views/users/edit.html.haml
%h1 Edit User Details

%form{ :action => '', :method => 'post' }
  %label Name:
  %input{ :type => 'text', :name => 'name', :placeholder => 'Enter Name' }
  %br
  %br
  %label Email:
  %input{ :type => 'text', :name => 'email', :placeholder => 'Enter Email' }
  %br
  %br
  %label Password:
  %input{ :type => 'text', :name => 'password', :placeholder => 'Enter Password' }
  %br
  %br
  %label Confirm Password:
  %input{ :type => 'text', :name => 'confirm_password', :placeholder => 'Confirm Password' }
  %br
  %br
  %label Gender:
  %input{ :type => 'text', :name => 'gender', :placeholder => 'Enter Gender' }
  %br
  %br
  %label Birth Date:
  %input{ :type => 'text', :name => 'dob', :placeholder => 'Enter Birth Date' }
  %br
  %br
  %input{ :type => 'submit', :value => 'Submit' }

app/views/users/index.html.haml
%h1 Welcome to Facebook
%p= link_to('Sign Up', new_user_path)
%table
  - @users.each do |user|
    %tr
      %td #{link_to(user.name, user_path(user))}
      %td #{link_to('Edit', edit_user_path(user))}
      %td #{link_to('Delete', user_path(user), method: 'DELETE', data: { confirm: 'Are you sure?' })}

app/views/users/new.html.haml
%h1 Register Here

= form_tag users_path, :method => :post do
  - if @user.errors.any?
    %h2
      = pluralize(@user.errors.count, "error")
      prohibited
      this article from being saved:
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg

  %p
    = label :user, :name, 'Name'
    %br/
    = text_field :user, :name
  %p
    = label :user, :email, 'Email'
    %br/
    = text_field :user, :email
  %p
    = label :user, :password, 'Password'
    %br/
    = text_field :user, :password
  %p
    = label :user, :confirm_password, 'Confirm Password'
    %br/
    = text_field :user, :password
  %p
    = label :user, :gender, 'Gender'
    %br/
    = text_field :user, :gender
  %p
    = label :user, :dob, 'Birth Date'
    %br/
    = text_field :user, :dob
  %p
    = submit_tag 'Submit'

app/views/users/show.html.haml
%h1 User Profile
%ul
  %li
    %strong Name:
    #{@user.name}
  %li
    %strong Email:
    #{@user.email}
  %li
    %strong Gender:
    #{@user.gender}
  %li
    %strong Birth Date:
    #{@user.dob}
=link_to('Address', user_address_path(@address))
=link_to('Create Post', new_user_post_path(@user))
-if @post != nil
  =link_to('Show Posts', user_post_path(@post))
  =link_to('Newsfeed', user_posts_path(@post))
=link_to('Back', users_path)